<a href="https://colab.research.google.com/github/talktovmpnow/CheatSheets/blob/master/Exercises/E0%20Pytorch/pytorch_fundamentals_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **PyTorch Fundamentals Exercise**



In [2]:
# Import all the necessary libraries here
import torch

### **Q1 Create a random tensor with shape `(7, 7)`**


In [3]:
tensor = torch.rand(7,7)
print(tensor)
print(tensor.shape)

tensor([[0.6474, 0.2811, 0.2764, 0.8949, 0.2089, 0.7059, 0.4326],
        [0.3950, 0.3083, 0.4742, 0.2881, 0.3516, 0.9444, 0.7799],
        [0.6195, 0.8735, 0.5084, 0.1591, 0.1482, 0.2225, 0.4459],
        [0.4455, 0.9433, 0.0121, 0.6736, 0.6954, 0.0260, 0.9575],
        [0.8854, 0.5110, 0.5628, 0.4334, 0.4332, 0.7022, 0.8211],
        [0.8364, 0.2269, 0.8777, 0.9306, 0.7656, 0.7699, 0.8988],
        [0.5726, 0.0155, 0.1923, 0.5020, 0.5027, 0.7026, 0.1535]])
torch.Size([7, 7])


### **Q2 Perform a matrix multiplication on the tensor from Q1 with another random tensor with shape `(1, 7)`**

In [5]:
tensor2 = torch.rand(1,7)
tensor_Matmul = torch.matmul(tensor, tensor2.T)
print(tensor_Matmul)
print(tensor2)
print(tensor2.T)
print(tensor_Matmul.shape)

tensor([[1.0697],
        [1.0273],
        [1.2832],
        [1.5704],
        [1.4191],
        [1.6785],
        [0.8006]])
tensor([[0.2530, 0.8209, 0.4211, 0.3562, 0.5445, 0.1430, 0.0584]])
tensor([[0.2530],
        [0.8209],
        [0.4211],
        [0.3562],
        [0.5445],
        [0.1430],
        [0.0584]])
torch.Size([7, 1])


### **Q3 Set the random seed to `0` and do Q1 & Q2 over again**

In [ ]:
import torch
torch.manual_seed(0)
# ### **Q1 Create a random tensor with shape `(7, 7)`**
tensor = torch.rand(7,7)
print(tensor)
print(tensor.shape)
# ### **Q2 Perform a matrix multiplication on the tensor from Q1 with another random tensor with shape `(1, 7)`**
tensor2 = torch.rand(1,7)
tensor_Matmul = torch.matmul(tensor, tensor2.T)
print(tensor_Matmul)
print(tensor2)
print(tensor2.T)
tensor_Matmul.shape


### **Q4 Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent?**
  * If there is, set the GPU random seed to `1234`

In [6]:
torch.cuda.manual_seed(1234)


### **Q5 Create two random tensors of shape `(2, 3)` and send them both to the GPU. Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed)**

In [9]:
torch.manual_seed(1234)
tensor_1 = torch.rand(2, 3)
tensor_2 = torch.rand(2, 3)

if torch.cuda.is_available():
  tensor_1 = tensor_1.to('cuda')
  tensor_2 = tensor_2.to('cuda')
  print(tensor_1)
  print(tensor_2)
else:
  print("CUDA is not available. Tensors remain on CPU.")
  print(tensor_1)


tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]], device='cuda:0')



### **Q6 Perform a matrix multiplication on the tensors you created in Q5**

In [ ]:
if torch.cuda.is_available():
  tensor_matmul = torch.matmul(tensor_1, tensor_2.T)
  print(tensor_matmul)
else:
  print("CUDA is not available. Matrix multiplication cannot be performed on GPU.")

### **Q7 Find the maximum and minimum values of the output of Q6**

In [ ]:
if torch.cuda.is_available():
  tensor_matmul = torch.matmul(tensor_1, tensor_2.T)
  max_val = torch.max(tensor_matmul)
  min_val = torch.min(tensor_matmul)
  print(f"Maximum value: {max_val}")
  print(f"Minimum value: {min_val}")
else:
  print("CUDA is not available. Matrix multiplication cannot be performed on GPU.")

### **Q8 Find the maximum and minimum index values of the output of Q6**

In [ ]:
# prompt: Find the maximum and minimum index values of the output of Q6

if torch.cuda.is_available():
  tensor_matmul = torch.matmul(tensor_1, tensor_2.T)
  max_index = torch.argmax(tensor_matmul)
  min_index = torch.argmin(tensor_matmul)
  print(f"Maximum index: {max_index}")
  print(f"Minimum index: {min_index}")
else:
  print("CUDA is not available. Matrix multiplication cannot be performed on GPU.")

### **Q9 Perform a matrix multiplication on the tensors you created in Q5 in `numpy` and convert the output to tensor**

In [ ]:
# prompt: Perform a matrix multiplication on the tensors you created in Q5 in numpy and convert the output to tensor

import torch
import numpy as np

# Assuming tensor_1 and tensor_2 are already defined and on the GPU (from Q5)
if torch.cuda.is_available():
  # Move tensors to CPU for numpy operations
  tensor_1_cpu = tensor_1.cpu()
  tensor_2_cpu = tensor_2.cpu()

  # Convert tensors to numpy arrays
  np_tensor_1 = tensor_1_cpu.numpy()
  np_tensor_2 = tensor_2_cpu.numpy()

  # Perform matrix multiplication in numpy
  np_matmul_result = np.matmul(np_tensor_1, np_tensor_2.T)

  # Convert the numpy array back to a PyTorch tensor
  tensor_matmul_result = torch.from_numpy(np_matmul_result)

  print("Numpy matrix multiplication result (converted to tensor):\n", tensor_matmul_result)
else:
  print("CUDA is not available. Cannot perform operations.")


### **Q10 Make a random tensor with shape `(1, 1, 1, 10)` and then convert it to a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape**

In [ ]:
# Your code here